# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 15 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 16 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 17 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 18 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 19 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 20 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 21 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 22 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 23 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 24 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 25 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 26 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 27 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 28 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 29 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 30 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 31 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 32 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 33 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 34 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 35 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 36 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 37 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 38 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 39 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 40 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 41 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 42 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 43 GPU_ID 0
python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 44 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 45 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 46 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 47 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 48 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 49 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_10 TEST.ITER 50 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 15 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 16 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 17 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 18 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 19 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 20 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 21 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 22 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 23 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 24 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 25 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 26 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 27 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 28 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 29 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 30 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 31 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 32 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 33 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 34 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 35 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 36 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 37 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 38 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 39 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 40 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 41 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 42 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 43 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 44 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 45 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 46 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 47 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 48 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 49 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA edited_val2014 TEST.ITER 50 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 15 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 16 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 17 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 18 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 19 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 20 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 21 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 22 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 23 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 24 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 25 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 26 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 27 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 28 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 29 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 30 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 31 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 32 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 33 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 34 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 35 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 36 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 37 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 38 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 39 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 40 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 41 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 42 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 43 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 44 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 45 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 46 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 47 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 48 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 49 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014_90 TEST.ITER 50 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 15 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 16 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 17 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 18 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 19 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 20 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 21 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 22 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 23 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 24 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 25 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 26 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 27 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 28 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 29 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 30 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 31 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 32 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 33 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 34 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 35 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 36 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 37 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 38 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 39 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 40 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 41 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 42 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 43 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 44 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 45 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 46 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 47 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 48 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 49 GPU_ID 0
# python /BS/vedika2/nobackup/snmn/exp_vqa/test_net_vqa.py --cfg exp_vqa/cfgs/vqa_v2_scratch_train_edited_train_25lr_finetuning.yaml TEST.SPLIT_VQA val2014 TEST.ITER 50 GPU_ID 0
